import type { Project, Developer, UserProfile } from './types'

export const mockDevelopers: Developer[] = [
  {
    id: 'dev-1',
    name: 'Alex Chen',
    initials: 'AC',
    avatarColor: '#7C3AED',
    tagline: 'Full-stack wizard building the impossible',
    skills: ['TypeScript', 'React', 'Next.js', 'PostgreSQL', 'AWS'],
    rating: 4.9,
    reviewCount: 87,
    completedProjects: 23,
    bio: 'Ex-Stripe engineer. I build fast, ship faster. Specialize in consumer apps with complex real-time requirements.',
    available: true,
    hourlyRate: 180,
    githubUrl: 'https://github.com',
    linkedinUrl: 'https://linkedin.com',
    portfolioItems: [
      { title: 'PaySync', description: 'Real-time payment reconciliation SaaS — $2M ARR', url: '#', image_url: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80', tech_stack: ['Next.js', 'Stripe', 'PostgreSQL'], role: 'Lead Engineer' },
      { title: 'FlowBoard', description: 'Kanban app with 50K MAU', url: '#', image_url: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&q=80', tech_stack: ['React', 'Node.js', 'Redis'], role: 'Solo Developer' },
    ],
  },
  {
    id: 'dev-2',
    name: 'Sarah Kim',
    initials: 'SK',
    avatarColor: '#06B6D4',
    tagline: 'ML engineer turning raw data into magic',
    skills: ['Python', 'PyTorch', 'FastAPI', 'LangChain', 'Docker'],
    rating: 4.8,
    reviewCount: 64,
    completedProjects: 18,
    bio: 'Former Google Brain researcher. I specialize in shipping production ML systems that actually scale.',
    available: true,
    hourlyRate: 220,
    githubUrl: 'https://github.com',
    linkedinUrl: 'https://linkedin.com',
    portfolioItems: [
      { title: 'DocuMind', description: 'AI document analyzer processing 1M docs/day', url: '#', image_url: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&q=80', tech_stack: ['Python', 'PyTorch', 'FastAPI'], role: 'ML Engineer' },
      { title: 'PriceAI', description: 'Dynamic pricing engine for e-commerce', url: '#', image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', tech_stack: ['Python', 'LangChain', 'Docker'], role: 'Lead ML Engineer' },
    ],
  },
  {
    id: 'dev-3',
    name: 'Marcus Rodriguez',
    initials: 'MR',
    avatarColor: '#EC4899',
    tagline: 'Mobile-first builder, zero compromise on UX',
    skills: ['React Native', 'Expo', 'Swift', 'Kotlin', 'Firebase'],
    rating: 4.7,
    reviewCount: 52,
    completedProjects: 15,
    bio: 'Built apps with 500K+ downloads. If it lives on a phone, I can build it beautifully.',
    available: false,
    hourlyRate: 160,
    githubUrl: 'https://github.com',
    portfolioItems: [
      { title: 'RunTrack Pro', description: '#1 running app in AU App Store', url: '#', image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80', tech_stack: ['React Native', 'Firebase', 'HealthKit'], role: 'Solo Developer' },
      { title: 'Mood.io', description: 'Mental health app, 200K+ users', url: '#', image_url: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80', tech_stack: ['React Native', 'Expo', 'Supabase'], role: 'Lead Mobile Engineer' },
    ],
  },
  {
    id: 'dev-4',
    name: 'Emma Wilson',
    initials: 'EW',
    avatarColor: '#F97316',
    tagline: 'Design-engineer hybrid, obsessed with craft',
    skills: ['Vue.js', 'Nuxt', 'Figma', 'CSS', 'Node.js'],
    rating: 4.6,
    reviewCount: 41,
    completedProjects: 12,
    bio: 'I blur the line between design and code. Every pixel matters, every interaction counts.',
    available: true,
    hourlyRate: 140,
    githubUrl: 'https://github.com',
    linkedinUrl: 'https://linkedin.com',
    portfolioItems: [
      { title: 'Palette Studio', description: 'Design tool used by 30K designers', url: '#', image_url: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&q=80', tech_stack: ['Vue.js', 'Node.js', 'Figma API'], role: 'Solo Developer' },
      { title: 'Spacer', description: 'Component spacing tool for Figma', url: '#', image_url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80', tech_stack: ['TypeScript', 'Figma Plugin API'], role: 'Solo Developer' },
    ],
  },
  {
    id: 'dev-5',
    name: 'Kai Nakamura',
    initials: 'KN',
    avatarColor: '#22C55E',
    tagline: 'Systems engineer, Rust enthusiast, perf obsessed',
    skills: ['Rust', 'Go', 'WebAssembly', 'C++', 'WASM'],
    rating: 4.8,
    reviewCount: 29,
    completedProjects: 9,
    bio: 'If performance matters, you want me. 10x faster is the baseline, not the goal.',
    available: true,
    hourlyRate: 200,
    githubUrl: 'https://github.com',
    portfolioItems: [
      { title: 'Velo', description: 'WASM-powered browser image processor', url: '#', image_url: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&q=80', tech_stack: ['Rust', 'WebAssembly', 'TypeScript'], role: 'Solo Developer' },
      { title: 'SigmaDB', description: 'Edge database written in Rust', url: '#', image_url: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&q=80', tech_stack: ['Rust', 'gRPC', 'WASM'], role: 'Solo Developer' },
    ],
  },
  {
    id: 'dev-6',
    name: 'Priya Sharma',
    initials: 'PS',
    avatarColor: '#EAB308',
    tagline: 'Full-stack + DevOps — I own the whole stack',
    skills: ['React', 'Python', 'Kubernetes', 'Terraform', 'Supabase'],
    rating: 4.9,
    reviewCount: 103,
    completedProjects: 27,
    bio: 'I build it, deploy it, monitor it. From idea to production in record time. 5 AppDrop projects shipped.',
    available: true,
    hourlyRate: 190,
    githubUrl: 'https://github.com',
    linkedinUrl: 'https://linkedin.com',
    portfolioItems: [
      { title: 'LaunchKit', description: 'Startup boilerplate used by 5K teams', url: '#', image_url: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80', tech_stack: ['React', 'Supabase', 'Terraform'], role: 'Solo Developer' },
      { title: 'OpsView', description: 'Infrastructure monitoring dashboard', url: '#', image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80', tech_stack: ['React', 'Python', 'Kubernetes', 'Grafana'], role: 'Lead Engineer' },
    ],
  },
]

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'NeuralNote',
    slug: 'neuralnote',
    tagline: 'Your voice → perfect structured notes, instantly',
    description: 'NeuralNote uses real-time speech recognition and AI to transform your spoken thoughts into beautifully organized, searchable notes. Stop typing — just think out loud.',
    category: 'AI',
    status: 'FUNDING',
    upvotes: 847,
    downvotes: 23,
    fundingCurrent: 34200,
    fundingGoal: 50000,
    backerCount: 342,
    gradient: 'from-purple-600 to-cyan-500',
    features: [
      'Real-time voice-to-text with AI structuring',
      'Automatic topic detection and categorization',
      'Meeting summary with action item extraction',
      'Export to Notion, Obsidian, or Markdown',
      'Cross-platform sync (iOS, Android, Web)',
      'Offline mode with background sync',
    ],
    milestones: [
      { id: 'm1', title: 'Core voice recognition engine', completed: true, dueDate: '2026-02-01' },
      { id: 'm2', title: 'AI structuring pipeline', completed: true, dueDate: '2026-03-01' },
      { id: 'm3', title: 'Mobile apps (iOS + Android)', completed: false, dueDate: '2026-05-15' },
      { id: 'm4', title: 'Public beta launch', completed: false, dueDate: '2026-07-01' },
    ],
    developer: mockDevelopers[1],
    comments: [
      { id: 'c1', author: 'Jake M.', initials: 'JM', avatarColor: '#7C3AED', content: 'This is exactly what I\'ve been waiting for. The current voice note apps are so bad.', createdAt: '2026-04-20', likes: 42 },
      { id: 'c2', author: 'Lena Park', initials: 'LP', avatarColor: '#06B6D4', content: 'Backed it. Hope the export to Obsidian is good — that\'s a dealbreaker for me.', createdAt: '2026-04-22', likes: 28 },
    ],
    tags: ['ai', 'notes', 'voice', 'productivity'],
    createdAt: '2026-01-15',
  },
  {
    id: '2',
    title: 'SprintFlow',
    slug: 'sprintflow',
    tagline: 'Kanban built for solo devs, zero team bloat',
    description: 'Linear for solo developers. SprintFlow strips away all the enterprise cruft and gives you a blazing-fast, keyboard-driven kanban board that gets out of your way.',
    category: 'PRODUCTIVITY',
    status: 'VOTING',
    upvotes: 1203,
    downvotes: 41,
    fundingCurrent: 0,
    fundingGoal: 30000,
    backerCount: 0,
    gradient: 'from-cyan-500 to-blue-600',
    features: [
      'Keyboard-first navigation (no mouse needed)',
      'Git integration — auto-create tickets from branches',
      'Time tracking built in',
      'Claude AI for task breakdown',
      'Offline-first with local storage',
    ],
    milestones: [
      { id: 'm1', title: 'Voting phase open', completed: true, dueDate: '2026-03-01' },
      { id: 'm2', title: 'Funding round opens', completed: false, dueDate: '2026-06-01' },
      { id: 'm3', title: 'Development start', completed: false, dueDate: '2026-07-01' },
    ],
    comments: [
      { id: 'c1', author: 'Tim B.', initials: 'TB', avatarColor: '#EC4899', content: 'Finally someone understands solo dev workflow. Linear is overkill for 1-person teams.', createdAt: '2026-05-01', likes: 89 },
      { id: 'c2', author: 'Anna W.', initials: 'AW', avatarColor: '#F97316', content: 'The keyboard-first approach is 🔥. Will back this immediately when funding opens.', createdAt: '2026-05-03', likes: 55 },
    ],
    tags: ['kanban', 'productivity', 'solo-dev', 'keyboard'],
    createdAt: '2026-02-20',
  },
  {
    id: '3',
    title: 'DietDrop',
    slug: 'dietdrop',
    tagline: 'Snap a photo. Know your macros. Done.',
    description: 'AI-powered food recognition with medical-grade macro tracking. Point your camera at any meal and get instant, accurate nutritional data without manually logging anything.',
    category: 'HEALTH',
    status: 'IN_DEV',
    upvotes: 2891,
    downvotes: 67,
    fundingCurrent: 30000,
    fundingGoal: 30000,
    backerCount: 891,
    gradient: 'from-pink-500 to-rose-600',
    features: [
      'Photo-based food recognition (98% accuracy)',
      'Barcode scanner with 50M+ food database',
      'Custom meal plans from a registered dietitian AI',
      'Integration with Apple Health and Fitbit',
      'Weekly progress reports with insights',
    ],
    milestones: [
      { id: 'm1', title: 'Food recognition model v1', completed: true, dueDate: '2026-01-01' },
      { id: 'm2', title: 'iOS beta released to backers', completed: true, dueDate: '2026-03-01' },
      { id: 'm3', title: 'Android version', completed: false, dueDate: '2026-06-15' },
      { id: 'm4', title: 'App Store launch', completed: false, dueDate: '2026-08-01' },
    ],
    developer: mockDevelopers[2],
    comments: [
      { id: 'c1', author: 'Rachel T.', initials: 'RT', avatarColor: '#22C55E', content: 'Been using the iOS beta. The food recognition is insanely accurate. This is the MyFitnessPal killer.', createdAt: '2026-04-01', likes: 134 },
    ],
    tags: ['health', 'nutrition', 'ai', 'fitness'],
    createdAt: '2025-11-10',
  },
  {
    id: '4',
    title: 'ArenaLobby',
    slug: 'arenal-obby',
    tagline: 'Cross-game tournaments, zero overhead',
    description: 'Organize and join esports tournaments across any game from a single platform. Automatic bracket management, prize pool escrow, and live stream integration.',
    category: 'GAMING',
    status: 'LIVE',
    upvotes: 2104,
    downvotes: 89,
    fundingCurrent: 75000,
    fundingGoal: 75000,
    backerCount: 1247,
    gradient: 'from-orange-500 to-red-600',
    features: [
      'Cross-game tournament creation',
      'Automated bracket management',
      'Built-in prize pool escrow',
      'Twitch/YouTube live stream integration',
      'Player stats and ELO ranking',
    ],
    milestones: [
      { id: 'm1', title: 'Platform MVP', completed: true, dueDate: '2025-09-01' },
      { id: 'm2', title: 'Prize pool escrow', completed: true, dueDate: '2025-11-01' },
      { id: 'm3', title: 'Mobile companion app', completed: true, dueDate: '2026-02-01' },
      { id: 'm4', title: '10K tournaments milestone', completed: false, dueDate: '2026-07-01' },
    ],
    developer: mockDevelopers[0],
    comments: [
      { id: 'c1', author: 'ProGamer99', initials: 'PG', avatarColor: '#F97316', content: 'We ran our entire 500-player CS2 tournament through this. Zero issues. 10/10.', createdAt: '2026-03-15', likes: 201 },
    ],
    tags: ['gaming', 'esports', 'tournaments', 'community'],
    createdAt: '2025-08-05',
  },
  {
    id: '5',
    title: 'ThreadWeave',
    slug: 'threadweave',
    tagline: 'Long-form newsletters with a social layer',
    description: 'Write long-form content that lives and breathes. ThreadWeave adds comments, reactions, and community features to newsletter publishing without sacrificing the reading experience.',
    category: 'SOCIAL',
    status: 'VOTING',
    upvotes: 678,
    downvotes: 31,
    fundingCurrent: 0,
    fundingGoal: 20000,
    backerCount: 0,
    gradient: 'from-pink-500 to-purple-600',
    features: [
      'Rich text editor with markdown support',
      'Inline comments and reactions',
      'Subscriber analytics dashboard',
      'Paid subscription tiers',
      'Cross-posting to X, LinkedIn, Mirror',
    ],
    milestones: [
      { id: 'm1', title: 'Community validation', completed: true, dueDate: '2026-04-01' },
      { id: 'm2', title: 'Funding goal', completed: false, dueDate: '2026-07-01' },
    ],
    comments: [
      { id: 'c1', author: 'Substack Refugee', initials: 'SR', avatarColor: '#A78BFA', content: 'The community layer is the missing piece. Substack comments are a ghost town.', createdAt: '2026-05-10', likes: 67 },
    ],
    tags: ['newsletter', 'writing', 'social', 'community'],
    createdAt: '2026-03-08',
  },
  {
    id: '6',
    title: 'StakeTrack',
    slug: 'staketrack',
    tagline: 'DeFi portfolio tracker that actually works',
    description: 'Aggregate your entire Web3 portfolio across 50+ chains with real-time yield tracking, impermanent loss calculations, and tax reporting built in.',
    category: 'FINTECH',
    status: 'FUNDING',
    upvotes: 445,
    downvotes: 18,
    fundingCurrent: 8700,
    fundingGoal: 25000,
    backerCount: 187,
    gradient: 'from-emerald-500 to-teal-600',
    features: [
      '50+ blockchain support',
      'Real-time DeFi yield tracking',
      'Impermanent loss calculator',
      'Tax reporting (CSV, TurboTax format)',
      'Price alerts and portfolio notifications',
    ],
    milestones: [
      { id: 'm1', title: 'Multi-chain data aggregation', completed: true, dueDate: '2026-03-01' },
      { id: 'm2', title: 'Tax reporting module', completed: false, dueDate: '2026-06-01' },
      { id: 'm3', title: 'Mobile app', completed: false, dueDate: '2026-09-01' },
    ],
    comments: [
      { id: 'c1', author: 'DeFi_Degen', initials: 'DD', avatarColor: '#6EE7B7', content: 'I\'ve been looking for something like this for years. Zerion is close but missing the tax stuff.', createdAt: '2026-05-05', likes: 43 },
    ],
    tags: ['defi', 'crypto', 'portfolio', 'fintech'],
    createdAt: '2026-02-14',
  },
  {
    id: '7',
    title: 'CodeReview.ai',
    slug: 'codereview-ai',
    tagline: 'AI code reviewer as a GitHub App',
    description: 'Automated code reviews that catch bugs, security issues, and style inconsistencies before they hit production. Trains on your codebase to understand your standards.',
    category: 'DEVELOPER_TOOLS',
    status: 'IN_DEV',
    upvotes: 1543,
    downvotes: 28,
    fundingCurrent: 60000,
    fundingGoal: 60000,
    backerCount: 743,
    gradient: 'from-cyan-500 to-indigo-600',
    features: [
      'Automated PR reviews with inline comments',
      'Security vulnerability detection',
      'Learns your team\'s coding standards',
      'Integrates with GitHub, GitLab, Bitbucket',
      'CI/CD pipeline integration',
    ],
    milestones: [
      { id: 'm1', title: 'Core review engine', completed: true, dueDate: '2026-02-01' },
      { id: 'm2', title: 'GitHub App integration', completed: true, dueDate: '2026-03-15' },
      { id: 'm3', title: 'Custom rule training', completed: false, dueDate: '2026-06-01' },
      { id: 'm4', title: 'GitLab + Bitbucket support', completed: false, dueDate: '2026-08-01' },
    ],
    developer: mockDevelopers[4],
    comments: [
      { id: 'c1', author: 'Senior Dev', initials: 'SD', avatarColor: '#67E8F9', content: 'This would save my team 5+ hours a week in code reviews. Can\'t wait.', createdAt: '2026-03-20', likes: 156 },
    ],
    tags: ['developer-tools', 'ai', 'code-review', 'github'],
    createdAt: '2025-12-01',
  },
  {
    id: '8',
    title: 'FlashGenius',
    slug: 'flashgenius',
    tagline: 'Spaced repetition flashcards — AI generated',
    description: 'Upload any document, textbook, or video transcript and FlashGenius generates optimized flashcard decks with spaced repetition scheduling proven to 10x retention.',
    category: 'EDUCATION',
    status: 'FUNDING',
    upvotes: 892,
    downvotes: 19,
    fundingCurrent: 22100,
    fundingGoal: 35000,
    backerCount: 521,
    gradient: 'from-yellow-500 to-orange-500',
    features: [
      'AI-generated flashcards from any document',
      'Spaced repetition algorithm (SM-2)',
      'Shared deck marketplace',
      'Progress analytics and weak-spot detection',
      'Offline study mode',
    ],
    milestones: [
      { id: 'm1', title: 'Card generation engine', completed: true, dueDate: '2026-03-01' },
      { id: 'm2', title: 'Spaced rep algorithm', completed: true, dueDate: '2026-04-01' },
      { id: 'm3', title: 'Deck marketplace', completed: false, dueDate: '2026-07-01' },
    ],
    developer: mockDevelopers[5],
    comments: [
      { id: 'c1', author: 'Med Student', initials: 'MS', avatarColor: '#FDE68A', content: 'Anki but with AI-generated cards? Take my money now.', createdAt: '2026-04-12', likes: 89 },
    ],
    tags: ['education', 'flashcards', 'ai', 'learning'],
    createdAt: '2026-02-01',
  },
  {
    id: '9',
    title: 'SyncMeetings',
    slug: 'syncmeetings',
    tagline: 'AI meeting summaries + auto action items',
    description: 'Join any meeting, get a perfect summary, and have action items automatically created in your project management tool of choice. Zero manual note-taking, ever.',
    category: 'PRODUCTIVITY',
    status: 'VOTING',
    upvotes: 534,
    downvotes: 22,
    fundingCurrent: 0,
    fundingGoal: 40000,
    backerCount: 0,
    gradient: 'from-blue-500 to-cyan-400',
    features: [
      'Zoom, Meet, Teams integration',
      'Real-time transcription and summarization',
      'Auto-create Jira/Linear/Notion tasks',
      'Searchable meeting history',
      'Follow-up email generation',
    ],
    milestones: [
      { id: 'm1', title: 'Idea validation', completed: true, dueDate: '2026-04-01' },
      { id: 'm2', title: 'Funding phase', completed: false, dueDate: '2026-07-01' },
    ],
    comments: [
      { id: 'c1', author: 'PM Life', initials: 'PL', avatarColor: '#67E8F9', content: 'Otter.ai but with actual project management integration. Yes please.', createdAt: '2026-05-15', likes: 44 },
    ],
    tags: ['meetings', 'ai', 'productivity', 'automation'],
    createdAt: '2026-03-22',
  },
  {
    id: '10',
    title: 'PitchDeck.ai',
    slug: 'pitchdeck-ai',
    tagline: 'Your startup story → investor-ready deck in minutes',
    description: 'Describe your startup in plain English and get a professional, VC-optimized pitch deck with real market data, competitor analysis, and compelling visuals.',
    category: 'AI',
    status: 'IN_DEV',
    upvotes: 1102,
    downvotes: 45,
    fundingCurrent: 45000,
    fundingGoal: 45000,
    backerCount: 623,
    gradient: 'from-violet-600 to-purple-800',
    features: [
      'AI-generated slides from text description',
      'Real market size data from Crunchbase/PitchBook',
      'Competitor landscape analysis',
      'Financial projection templates',
      'One-click export to PowerPoint/PDF',
    ],
    milestones: [
      { id: 'm1', title: 'Slide generation engine', completed: true, dueDate: '2026-02-15' },
      { id: 'm2', title: 'Market data integration', completed: true, dueDate: '2026-04-01' },
      { id: 'm3', title: 'Design templates library', completed: false, dueDate: '2026-06-01' },
    ],
    developer: mockDevelopers[1],
    comments: [
      { id: 'c1', author: 'First-time Founder', initials: 'FF', avatarColor: '#A78BFA', content: 'I spent 40 hours on my last pitch deck. If this works, it\'s worth 10x the price.', createdAt: '2026-04-05', likes: 78 },
    ],
    tags: ['ai', 'startups', 'fundraising', 'presentations'],
    createdAt: '2025-12-20',
  },
  {
    id: '11',
    title: 'BeatDrop',
    slug: 'beatdrop',
    tagline: 'Collaborative music production, in your browser',
    description: 'Make beats with friends in real-time, right in the browser. No downloads, no DAW subscription, no learning curve. Professional results from day one.',
    category: 'SOCIAL',
    status: 'FUNDING',
    upvotes: 723,
    downvotes: 34,
    fundingCurrent: 15000,
    fundingGoal: 40000,
    backerCount: 298,
    gradient: 'from-fuchsia-600 to-pink-500',
    features: [
      'Real-time collaborative sessions (up to 8 people)',
      'Browser-based DAW (no install)',
      '1,000+ professional samples',
      'Export stems and master track',
      'Social sharing and beat marketplace',
    ],
    milestones: [
      { id: 'm1', title: 'Core audio engine', completed: true, dueDate: '2026-03-01' },
      { id: 'm2', title: 'Real-time collab engine', completed: false, dueDate: '2026-06-15' },
      { id: 'm3', title: 'Sample library', completed: false, dueDate: '2026-08-01' },
    ],
    comments: [
      { id: 'c1', author: 'Beat Maker', initials: 'BM', avatarColor: '#F9A8D4', content: 'SoundTrap but actually good? I\'m so in. The collab angle is huge.', createdAt: '2026-05-02', likes: 62 },
    ],
    tags: ['music', 'collab', 'audio', 'creator'],
    createdAt: '2026-02-28',
  },
  {
    id: '12',
    title: 'LegalEasy',
    slug: 'legaleasy',
    tagline: 'Contracts in plain English, finally',
    description: 'Upload any contract and get a plain-English summary, risk analysis, and negotiation suggestions. Know exactly what you\'re signing before you sign it.',
    category: 'FINTECH',
    status: 'VOTING',
    upvotes: 456,
    downvotes: 12,
    fundingCurrent: 0,
    fundingGoal: 35000,
    backerCount: 0,
    gradient: 'from-teal-500 to-green-600',
    features: [
      'AI contract analysis in 30 seconds',
      'Risk scoring and red flag detection',
      'Plain-English clause explanations',
      'Negotiation points suggestions',
      'Legal precedent references',
    ],
    milestones: [
      { id: 'm1', title: 'Idea validation complete', completed: true, dueDate: '2026-04-01' },
      { id: 'm2', title: 'Legal compliance review', completed: false, dueDate: '2026-07-01' },
    ],
    comments: [
      { id: 'c1', author: 'Freelancer', initials: 'FL', avatarColor: '#6EE7B7', content: 'I\'ve signed things I didn\'t understand because lawyers are too expensive. This is needed.', createdAt: '2026-05-20', likes: 91 },
    ],
    tags: ['legal', 'contracts', 'ai', 'fintech'],
    createdAt: '2026-04-01',
  },
  {
    id: '13',
    title: 'GamePulse',
    slug: 'gamepulse',
    tagline: 'Real-time esports stats, all games, one dashboard',
    description: 'The Bloomberg Terminal for esports. Track live match data, player performance, team analytics, and betting odds across every major esports title.',
    category: 'GAMING',
    status: 'LIVE',
    upvotes: 1876,
    downvotes: 71,
    fundingCurrent: 55000,
    fundingGoal: 55000,
    backerCount: 1102,
    gradient: 'from-red-600 to-orange-500',
    features: [
      'Live match data from 15+ esports titles',
      'Player and team performance analytics',
      'Historical data going back 5 years',
      'API access for developers',
      'Discord bot integration',
    ],
    milestones: [
      { id: 'm1', title: 'Data pipeline MVP', completed: true, dueDate: '2025-10-01' },
      { id: 'm2', title: 'Dashboard v1.0', completed: true, dueDate: '2025-12-01' },
      { id: 'm3', title: 'API beta program', completed: true, dueDate: '2026-03-01' },
      { id: 'm4', title: '50K users milestone', completed: false, dueDate: '2026-08-01' },
    ],
    developer: mockDevelopers[0],
    comments: [
      { id: 'c1', author: 'EsportsAnalyst', initials: 'EA', avatarColor: '#FED7AA', content: 'This has replaced 3 other tools I was using. The LoL and Dota coverage is incredible.', createdAt: '2026-04-28', likes: 178 },
    ],
    tags: ['gaming', 'esports', 'analytics', 'data'],
    createdAt: '2025-09-15',
  },
  {
    id: '14',
    title: 'DevPulse',
    slug: 'devpulse',
    tagline: 'Your GitHub + GitLab + Jira, one beautiful dashboard',
    description: 'Unified developer activity dashboard that pulls from all your tools. See your real output, identify bottlenecks, and ship faster with intelligent suggestions.',
    category: 'DEVELOPER_TOOLS',
    status: 'VOTING',
    upvotes: 390,
    downvotes: 14,
    fundingCurrent: 0,
    fundingGoal: 20000,
    backerCount: 0,
    gradient: 'from-sky-500 to-blue-700',
    features: [
      'GitHub, GitLab, Jira, Linear integration',
      'Personal velocity tracking',
      'Team standup auto-generation',
      'Context switching cost analysis',
      'Weekly digest emails',
    ],
    milestones: [
      { id: 'm1', title: 'Idea submission', completed: true, dueDate: '2026-05-01' },
      { id: 'm2', title: 'Funding phase', completed: false, dueDate: '2026-08-01' },
    ],
    comments: [
      { id: 'c1', author: 'IC Engineer', initials: 'IE', avatarColor: '#67E8F9', content: 'Perfect for proving your impact in perf reviews without self-reporting everything.', createdAt: '2026-05-22', likes: 38 },
    ],
    tags: ['developer-tools', 'analytics', 'productivity', 'github'],
    createdAt: '2026-04-28',
  },
  {
    id: '15',
    title: 'HealthLedger',
    slug: 'healthledger',
    tagline: 'Own your health data. Share it on your terms.',
    description: 'A universal health data wallet that aggregates records from all your providers, wearables, and apps. Share specific data with doctors without handing over everything.',
    category: 'HEALTH',
    status: 'VOTING',
    upvotes: 301,
    downvotes: 9,
    fundingCurrent: 0,
    fundingGoal: 50000,
    backerCount: 0,
    gradient: 'from-rose-500 to-pink-600',
    features: [
      'FHIR-compliant health data aggregation',
      'Selective sharing with granular permissions',
      'AI-powered health insights',
      'Integration with Apple Health, Fitbit, Garmin',
      'Emergency access for family members',
    ],
    milestones: [
      { id: 'm1', title: 'Privacy architecture design', completed: true, dueDate: '2026-04-15' },
      { id: 'm2', title: 'Community validation', completed: true, dueDate: '2026-05-15' },
      { id: 'm3', title: 'Funding phase open', completed: false, dueDate: '2026-08-01' },
    ],
    comments: [
      { id: 'c1', author: 'Privacy Advocate', initials: 'PA', avatarColor: '#F9A8D4', content: 'This is critical infrastructure for the future of healthcare. Supporting immediately.', createdAt: '2026-05-25', likes: 52 },
    ],
    tags: ['health', 'privacy', 'data', 'wearables'],
    createdAt: '2026-04-10',
  },
]

export const mockUser: UserProfile = {
  id: 'user-1',
  name: 'Jordan Blake',
  username: 'jordanblake',
  initials: 'JB',
  avatarColor: '#7C3AED',
  joinedAt: '2025-09-01',
  stats: {
    totalVotes: 247,
    totalBacked: 8,
    totalSubmitted: 3,
    reputation: 1840,
    totalFunded: 3200,
  },
  badges: [
    {
      id: 'b1',
      name: 'Trend Setter',
      description: 'Voted on 5+ ideas that later went LIVE',
      emoji: '🔥',
      color: 'orange',
      earned: true,
    },
    {
      id: 'b2',
      name: 'Super Backer',
      description: 'Backed 5+ projects that shipped successfully',
      emoji: '💎',
      color: 'cyan',
      earned: true,
    },
    {
      id: 'b3',
      name: 'Early Adopter',
      description: 'Joined AppDrop in the first 90 days',
      emoji: '⚡',
      color: 'purple',
      earned: true,
    },
    {
      id: 'b4',
      name: 'Idea Machine',
      description: 'Submitted 3+ ideas to the marketplace',
      emoji: '🧠',
      color: 'pink',
      earned: true,
    },
    {
      id: 'b5',
      name: 'Top Builder',
      description: 'Claim a project and ship it to LIVE status',
      emoji: '🏆',
      color: 'orange',
      earned: false,
    },
    {
      id: 'b6',
      name: 'Community Voice',
      description: 'Leave 100+ helpful comments',
      emoji: '📣',
      color: 'cyan',
      earned: false,
    },
  ],
}
