import type { Project, Developer, UserProfile } from './types'

export const mockDevelopers: Developer[] = [
  {
    id: 'dev-1',
    name: 'Alex Chen',
    initials: 'AC',
    avatarColor: '#7C3AED',
    tagline: 'Full-stack engineer — ex-Stripe, 12 AppDrop projects shipped',
    skills: ['TypeScript', 'React', 'Next.js', 'PostgreSQL', 'AWS'],
    rating: 4.9,
    reviewCount: 87,
    completedProjects: 23,
    bio: 'Ex-Stripe engineer. I specialise in consumer products with real-time requirements. I look for validated AppDrop ideas with strong waitlist numbers before taking a project.',
    available: true,
    hourlyRate: 180,
    githubUrl: 'https://github.com',
    linkedinUrl: 'https://linkedin.com',
    portfolioItems: [
      { title: 'PaySync', description: 'Real-time payment reconciliation SaaS — $2M ARR. Validated on AppDrop with 3,400 upvotes before first line of code was written.', url: '#', image_url: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80', tech_stack: ['Next.js', 'Stripe', 'PostgreSQL'], role: 'Lead Engineer' },
      { title: 'FlowBoard', description: 'Kanban for solo devs — 50K MAU. Started as a validated AppDrop idea.', url: '#', image_url: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&q=80', tech_stack: ['React', 'Node.js', 'Redis'], role: 'Solo Developer' },
    ],
  },
  {
    id: 'dev-2',
    name: 'Sarah Kim',
    initials: 'SK',
    avatarColor: '#06B6D4',
    tagline: 'ML engineer — I only build things the market wants',
    skills: ['Python', 'PyTorch', 'FastAPI', 'LangChain', 'Docker'],
    rating: 4.8,
    reviewCount: 64,
    completedProjects: 18,
    bio: 'Former Google Brain researcher. I only claim projects that have cleared STRONG SIGNAL or better on AppDrop — validation data tells me more than any brief.',
    available: true,
    hourlyRate: 220,
    githubUrl: 'https://github.com',
    linkedinUrl: 'https://linkedin.com',
    portfolioItems: [
      { title: 'DocuMind', description: 'AI document analyzer, 1M docs/day. Claimed after the AppDrop idea hit 2,800 upvotes and 400+ waitlist.', url: '#', image_url: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&q=80', tech_stack: ['Python', 'PyTorch', 'FastAPI'], role: 'ML Engineer' },
      { title: 'PriceAI', description: 'Dynamic pricing engine for e-commerce. Validated demand before I wrote a single API endpoint.', url: '#', image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80', tech_stack: ['Python', 'LangChain', 'Docker'], role: 'Lead ML Engineer' },
    ],
  },
  {
    id: 'dev-3',
    name: 'Marcus Rodriguez',
    initials: 'MR',
    avatarColor: '#EC4899',
    tagline: 'Mobile-first builder — 500K+ downloads across AppDrop projects',
    skills: ['React Native', 'Expo', 'Swift', 'Kotlin', 'Firebase'],
    rating: 4.7,
    reviewCount: 52,
    completedProjects: 15,
    bio: 'Built apps with 500K+ downloads. I browse AppDrop weekly — a validated idea with a real waitlist is worth more than any design spec.',
    available: false,
    hourlyRate: 160,
    githubUrl: 'https://github.com',
    portfolioItems: [
      { title: 'RunTrack Pro', description: '#1 running app in AU App Store. Originated as an AppDrop validation with 1,900 upvotes.', url: '#', image_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80', tech_stack: ['React Native', 'Firebase', 'HealthKit'], role: 'Solo Developer' },
      { title: 'Mood.io', description: 'Mental health app, 200K+ users. Built after community validation confirmed the need.', url: '#', image_url: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80', tech_stack: ['React Native', 'Expo', 'Supabase'], role: 'Lead Mobile Engineer' },
    ],
  },
  {
    id: 'dev-4',
    name: 'Emma Wilson',
    initials: 'EW',
    avatarColor: '#F97316',
    tagline: 'Design-engineer hybrid — I make validated ideas beautiful',
    skills: ['Vue.js', 'Nuxt', 'Figma', 'CSS', 'Node.js'],
    rating: 4.6,
    reviewCount: 41,
    completedProjects: 12,
    bio: 'I blur the line between design and code. I use AppDrop validation scores to decide which ideas are worth the craft — PROVEN DEMAND gets my full attention.',
    available: true,
    hourlyRate: 140,
    githubUrl: 'https://github.com',
    linkedinUrl: 'https://linkedin.com',
    portfolioItems: [
      { title: 'Palette Studio', description: 'Design tool used by 30K designers. Community validated, then built beautifully.', url: '#', image_url: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&q=80', tech_stack: ['Vue.js', 'Node.js', 'Figma API'], role: 'Solo Developer' },
      { title: 'Spacer', description: 'Component spacing tool for Figma — simple idea, high validation signal.', url: '#', image_url: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80', tech_stack: ['TypeScript', 'Figma Plugin API'], role: 'Solo Developer' },
    ],
  },
  {
    id: 'dev-5',
    name: 'Kai Nakamura',
    initials: 'KN',
    avatarColor: '#22C55E',
    tagline: 'Systems engineer — Rust, Go, and validated product requirements',
    skills: ['Rust', 'Go', 'WebAssembly', 'C++', 'WASM'],
    rating: 4.8,
    reviewCount: 29,
    completedProjects: 9,
    bio: 'Performance is my baseline. I use AppDrop\'s validation data as my product spec — real user demand signals save months of building the wrong thing.',
    available: true,
    hourlyRate: 200,
    githubUrl: 'https://github.com',
    portfolioItems: [
      { title: 'Velo', description: 'WASM-powered browser image processor. Claimed after validation confirmed the edge-performance use case.', url: '#', image_url: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&q=80', tech_stack: ['Rust', 'WebAssembly', 'TypeScript'], role: 'Solo Developer' },
      { title: 'SigmaDB', description: 'Edge database written in Rust — 400+ developer upvotes before a single commit.', url: '#', image_url: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&q=80', tech_stack: ['Rust', 'gRPC', 'WASM'], role: 'Solo Developer' },
    ],
  },
  {
    id: 'dev-6',
    name: 'Priya Sharma',
    initials: 'PS',
    avatarColor: '#EAB308',
    tagline: 'Full-stack + DevOps — 5 AppDrop ideas shipped to LIVE',
    skills: ['React', 'Python', 'Kubernetes', 'Terraform', 'Supabase'],
    rating: 4.9,
    reviewCount: 103,
    completedProjects: 27,
    bio: 'I\'ve shipped 5 AppDrop projects from validated idea to production. The waitlist data on this platform tells you more about PMF than any user interview.',
    available: true,
    hourlyRate: 190,
    githubUrl: 'https://github.com',
    linkedinUrl: 'https://linkedin.com',
    portfolioItems: [
      { title: 'LaunchKit', description: 'Startup boilerplate used by 5K teams. Validated on AppDrop, built in 8 weeks.', url: '#', image_url: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&q=80', tech_stack: ['React', 'Supabase', 'Terraform'], role: 'Solo Developer' },
      { title: 'OpsView', description: 'Infrastructure monitoring dashboard — claimed after 1,600 dev-tool upvotes confirmed the gap.', url: '#', image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80', tech_stack: ['React', 'Python', 'Kubernetes', 'Grafana'], role: 'Lead Engineer' },
    ],
  },
]

export const mockProjects: Project[] = [
  {
    id: '1',
    title: 'NeuralNote',
    slug: 'neuralnote',
    tagline: 'Voice → structured notes. Stop typing in meetings.',
    description: '847 upvotes and 342 waitlist signups confirmed the gap is real: everyone takes meeting notes but nobody reads them later. NeuralNote uses real-time AI to convert speech into searchable, structured notes with action items automatically extracted. Currently in funding — iOS and Android apps are the next milestone.',
    category: 'AI',
    status: 'FUNDING',
    upvotes: 847,
    downvotes: 23,
    fundingCurrent: 34200,
    fundingGoal: 50000,
    backerCount: 342,
    gradient: 'from-purple-600 to-cyan-500',
    features: [
      'Real-time voice-to-text with AI structuring',
      'Automatic action item extraction',
      'Meeting summary in 5 bullets, not a transcript wall',
      'Integrates with Notion, Linear, and Jira',
      'Offline mode with background sync',
    ],
    milestones: [
      { id: 'm1', title: 'Validation phase — 847 upvotes, 342 waitlist', completed: true, dueDate: '2026-02-01' },
      { id: 'm2', title: 'Core AI transcription + structuring engine', completed: true, dueDate: '2026-03-01' },
      { id: 'm3', title: 'iOS + Android apps', completed: false, dueDate: '2026-05-15' },
      { id: 'm4', title: 'Public launch to waitlist', completed: false, dueDate: '2026-07-01' },
    ],
    developer: mockDevelopers[1],
    comments: [
      { id: 'c1', author: 'Jake M.', initials: 'JM', avatarColor: '#7C3AED', content: 'Backed. I spend half my 1:1s typing instead of listening. This fixes that.', createdAt: '2026-04-20', likes: 42 },
      { id: 'c2', author: 'Lena Park', initials: 'LP', avatarColor: '#06B6D4', content: 'The Obsidian export is the dealbreaker for me — glad it\'s in the roadmap.', createdAt: '2026-04-22', likes: 28 },
    ],
    tags: ['ai', 'notes', 'voice', 'productivity'],
    createdAt: '2026-01-15',
  },
  {
    id: '2',
    title: 'SprintFlow',
    slug: 'sprintflow',
    tagline: 'Project management built for one person, not a team of 20',
    description: 'I\'ve tried Jira, Linear, Notion, and Trello for solo work. Every single one assumes you\'re part of a team — sprints, standups, story points, velocity charts for a person who ships alone. Testing if solo developers and indie founders want a keyboard-first, zero-ceremony board that gets out of the way and just tracks what you\'re building.',
    category: 'PRODUCTIVITY',
    status: 'VOTING',
    upvotes: 1203,
    downvotes: 41,
    fundingCurrent: 0,
    fundingGoal: 30000,
    backerCount: 0,
    waitlistCount: 280,
    gradient: 'from-cyan-500 to-blue-600',
    features: [
      'Keyboard-first: open laptop and be exactly where you left off',
      'Git branch → ticket creation, automatically',
      'Single-user velocity (no team standup theater)',
      'AI task breakdown — paste a goal, get daily subtasks',
      'Weekly review built in, not bolted on',
    ],
    milestones: [
      { id: 'm1', title: 'Validation open — testing demand', completed: true, dueDate: '2026-03-01' },
      { id: 'm2', title: 'Funding round opens if validation clears', completed: false, dueDate: '2026-06-01' },
      { id: 'm3', title: 'Development start', completed: false, dueDate: '2026-07-01' },
    ],
    comments: [
      { id: 'c1', author: 'Tim B.', initials: 'TB', avatarColor: '#EC4899', content: 'I\'ve rebuilt my Notion setup 4 times trying to make it work for solo dev. This is exactly the gap I feel every day.', createdAt: '2026-05-01', likes: 89 },
      { id: 'c2', author: 'Anna W.', initials: 'AW', avatarColor: '#F97316', content: 'On the waitlist. Linear is the closest thing but still assumes sprints and planning ceremonies I don\'t have.', createdAt: '2026-05-03', likes: 55 },
    ],
    tags: ['solo-dev', 'kanban', 'productivity', 'keyboard-first'],
    createdAt: '2026-02-20',
  },
  {
    id: '3',
    title: 'DietDrop',
    slug: 'dietdrop',
    tagline: 'Snap a photo. Know your macros. Done.',
    description: '2,891 upvotes made this AppDrop\'s most-validated health idea. The community insight: generic diet advice fails because it ignores individual biology. DietDrop uses AI photo recognition plus optional DNA data integration to generate nutrition guidance that\'s actually personalised to your metabolism — not a one-size-fits-all calorie counter. Currently in active development.',
    category: 'HEALTH',
    status: 'IN_DEV',
    upvotes: 2891,
    downvotes: 67,
    fundingCurrent: 30000,
    fundingGoal: 30000,
    backerCount: 891,
    gradient: 'from-pink-500 to-rose-600',
    features: [
      'Photo-based food recognition (98% accuracy on 50M+ items)',
      'Optional DNA data integration for personalised plans',
      'Weekly insights report with actionable changes',
      'Integration with Apple Health and Fitbit',
      'Barcode scanner with full nutritional breakdown',
    ],
    milestones: [
      { id: 'm1', title: 'Validation phase — 2,891 upvotes, 567 waitlist', completed: true, dueDate: '2026-01-01' },
      { id: 'm2', title: 'Food recognition model v1', completed: true, dueDate: '2026-02-01' },
      { id: 'm3', title: 'iOS beta to waitlist backers', completed: true, dueDate: '2026-03-01' },
      { id: 'm4', title: 'Android + App Store launch', completed: false, dueDate: '2026-08-01' },
    ],
    developer: mockDevelopers[2],
    comments: [
      { id: 'c1', author: 'Rachel T.', initials: 'RT', avatarColor: '#22C55E', content: 'Using the iOS beta. The food recognition is insanely accurate. This is the MyFitnessPal replacement I\'ve been waiting for.', createdAt: '2026-04-01', likes: 134 },
    ],
    tags: ['health', 'nutrition', 'ai', 'fitness'],
    createdAt: '2025-11-10',
  },
  {
    id: '4',
    title: 'ArenaLobby',
    slug: 'arenalobby',
    tagline: 'Skill-matched gaming tournaments with real stakes',
    description: 'Validated by 2,104 upvotes answering one question: would competitive gamers pay to play in skill-matched brackets with real prize money? The answer was obvious. ArenaLobby is now live with 1,247 backers — cross-game tournament creation, ELO matchmaking, escrow-backed prize pools, and Twitch integration.',
    category: 'GAMING',
    status: 'LIVE',
    upvotes: 2104,
    downvotes: 89,
    fundingCurrent: 75000,
    fundingGoal: 75000,
    backerCount: 1247,
    gradient: 'from-orange-500 to-red-600',
    features: [
      'ELO-based matchmaking across 15+ games',
      'Secure escrow for prize pools',
      'Automated bracket management',
      'Twitch/YouTube live stream integration',
      'Anti-cheat verification layer',
    ],
    milestones: [
      { id: 'm1', title: 'Validation + funding — 2,104 upvotes', completed: true, dueDate: '2025-09-01' },
      { id: 'm2', title: 'Platform MVP with escrow', completed: true, dueDate: '2025-11-01' },
      { id: 'm3', title: 'Mobile companion app', completed: true, dueDate: '2026-02-01' },
      { id: 'm4', title: '10K tournaments milestone', completed: false, dueDate: '2026-07-01' },
    ],
    developer: mockDevelopers[0],
    comments: [
      { id: 'c1', author: 'ProGamer99', initials: 'PG', avatarColor: '#F97316', content: 'Ran our entire 500-player CS2 tournament through this. Zero issues. The matchmaking is genuinely good.', createdAt: '2026-03-15', likes: 201 },
    ],
    tags: ['gaming', 'esports', 'tournaments', 'competitive'],
    createdAt: '2025-08-05',
  },
  {
    id: '5',
    title: 'ThreadWeave',
    slug: 'threadweave',
    tagline: 'What if your newsletter had a real community underneath it?',
    description: 'Published 6 issues of my newsletter — 800 subscribers, 60% open rate, zero public conversation. Email is one-way by design and that limits what writing can become. Testing demand for a platform where long-form content and community live together from day one, not bolted together like Substack trying to retrofit forums.',
    category: 'SOCIAL',
    status: 'VOTING',
    upvotes: 185,
    downvotes: 14,
    fundingCurrent: 0,
    fundingGoal: 20000,
    backerCount: 0,
    waitlistCount: 12,
    gradient: 'from-pink-500 to-purple-600',
    features: [
      'Rich text editor that doesn\'t get in the way',
      'Inline paragraph comments — like a book club on every piece',
      'Subscriber tiers with community access gating',
      'Discussion threads per issue, not a generic forum',
      'Cross-post to X and LinkedIn from one place',
    ],
    milestones: [
      { id: 'm1', title: 'Validation phase — collecting demand signals', completed: true, dueDate: '2026-04-01' },
      { id: 'm2', title: 'Funding opens if signal clears', completed: false, dueDate: '2026-07-01' },
    ],
    comments: [
      { id: 'c1', author: 'Substack Writer', initials: 'SW', avatarColor: '#A78BFA', content: 'The problem with Substack comments is they feel like shouting into a void. A proper community layer changes the whole incentive for writing.', createdAt: '2026-05-10', likes: 67 },
    ],
    tags: ['newsletter', 'community', 'writing', 'creator'],
    createdAt: '2026-03-08',
  },
  {
    id: '6',
    title: 'StakeTrack',
    slug: 'staketrack',
    tagline: 'DeFi portfolio tracker that actually handles tax time',
    description: '445 upvotes from people burned by DeFi tax season confirmed the gap. Tracking yield, impermanent loss, and cost basis across 50+ chains manually is a nightmare — most tools either miss chains or can\'t produce anything tax authorities accept. StakeTrack is now in funding with automated tax reporting as the core differentiator.',
    category: 'FINTECH',
    status: 'FUNDING',
    upvotes: 445,
    downvotes: 18,
    fundingCurrent: 8700,
    fundingGoal: 25000,
    backerCount: 187,
    gradient: 'from-emerald-500 to-teal-600',
    features: [
      '50+ blockchain support',
      'Real-time DeFi yield tracking',
      'Impermanent loss calculator',
      'Tax reporting in CSV and TurboTax format',
      'Price alerts and portfolio rebalance notifications',
    ],
    milestones: [
      { id: 'm1', title: 'Validation — 445 upvotes, 187 waitlist signups', completed: true, dueDate: '2026-03-01' },
      { id: 'm2', title: 'Multi-chain data aggregation', completed: true, dueDate: '2026-04-01' },
      { id: 'm3', title: 'Tax reporting module', completed: false, dueDate: '2026-06-01' },
      { id: 'm4', title: 'Mobile app', completed: false, dueDate: '2026-09-01' },
    ],
    comments: [
      { id: 'c1', author: 'DeFi_Degen', initials: 'DD', avatarColor: '#6EE7B7', content: 'Zerion is close but the tax reporting is useless. This is the one thing actually missing from every DeFi tool.', createdAt: '2026-05-05', likes: 43 },
    ],
    tags: ['defi', 'crypto', 'portfolio', 'tax'],
    createdAt: '2026-02-14',
  },
  {
    id: '7',
    title: 'CodeReview.ai',
    slug: 'codereview-ai',
    tagline: 'AI code reviewer trained on your team\'s standards',
    description: '1,543 upvotes from developers who spend 5+ hours a week reviewing PRs confirmed this was worth building. CodeReview.ai is an AI GitHub App that learns your codebase conventions, flags security issues, and gives inline PR feedback — so senior engineers stop being review bottlenecks. Currently 60% funded.',
    category: 'DEVELOPER_TOOLS',
    status: 'IN_DEV',
    upvotes: 1543,
    downvotes: 28,
    fundingCurrent: 60000,
    fundingGoal: 60000,
    backerCount: 743,
    gradient: 'from-cyan-500 to-indigo-600',
    features: [
      'Automated PR reviews with inline comments',
      'Security vulnerability detection',
      'Learns your team\'s conventions and style',
      'GitHub, GitLab, Bitbucket integration',
      'CI/CD pipeline blocking for critical issues',
    ],
    milestones: [
      { id: 'm1', title: 'Validation — 1,543 upvotes, 743 waitlist', completed: true, dueDate: '2026-02-01' },
      { id: 'm2', title: 'Core review engine + GitHub App', completed: true, dueDate: '2026-03-15' },
      { id: 'm3', title: 'Custom rule training on codebase', completed: false, dueDate: '2026-06-01' },
      { id: 'm4', title: 'GitLab + Bitbucket support', completed: false, dueDate: '2026-08-01' },
    ],
    developer: mockDevelopers[4],
    comments: [
      { id: 'c1', author: 'Senior Dev', initials: 'SD', avatarColor: '#67E8F9', content: 'We onboard 2-3 junior devs per quarter. This would save 5+ hours a week in review cycles alone.', createdAt: '2026-03-20', likes: 156 },
    ],
    tags: ['developer-tools', 'ai', 'code-review', 'github'],
    createdAt: '2025-12-01',
  },
  {
    id: '8',
    title: 'FlashGenius',
    slug: 'flashgenius',
    tagline: 'Upload any doc. Get a perfect flashcard deck in 30 seconds.',
    description: '892 upvotes from students and lifelong learners confirmed the problem: creating good flashcards takes almost as long as studying. FlashGenius generates spaced-repetition decks from any document, textbook, or video transcript — so you spend time learning, not formatting cards. In active funding.',
    category: 'EDUCATION',
    status: 'FUNDING',
    upvotes: 892,
    downvotes: 19,
    fundingCurrent: 22100,
    fundingGoal: 35000,
    backerCount: 521,
    gradient: 'from-yellow-500 to-orange-500',
    features: [
      'AI card generation from PDF, DOCX, or YouTube transcript',
      'Spaced repetition algorithm (proven SM-2 model)',
      'Shared deck marketplace',
      'Weak-spot detection and focused drilling',
      'Offline study mode',
    ],
    milestones: [
      { id: 'm1', title: 'Validation — 892 upvotes, 521 waitlist', completed: true, dueDate: '2026-03-01' },
      { id: 'm2', title: 'Card generation + spaced rep engine', completed: true, dueDate: '2026-04-01' },
      { id: 'm3', title: 'Deck marketplace', completed: false, dueDate: '2026-07-01' },
    ],
    developer: mockDevelopers[5],
    comments: [
      { id: 'c1', author: 'Med Student', initials: 'MS', avatarColor: '#FDE68A', content: 'Anki with AI-generated cards? I\'ve spent more time making Anki decks than using them. This solves the actual problem.', createdAt: '2026-04-12', likes: 89 },
    ],
    tags: ['education', 'flashcards', 'ai', 'learning'],
    createdAt: '2026-02-01',
  },
  {
    id: '9',
    title: 'SyncMeetings',
    slug: 'syncmeetings',
    tagline: 'Stop taking meeting notes. Let the AI do it.',
    description: 'I have 6-8 meetings a week. I spend 15 minutes in each one half-listening while I type. Tried Otter, Fireflies, and Read.ai — they transcribe but they don\'t understand. Testing whether people want something that joins your calls, writes a genuinely useful summary (not a transcript wall), and creates real tasks in your project tool automatically.',
    category: 'PRODUCTIVITY',
    status: 'VOTING',
    upvotes: 320,
    downvotes: 11,
    fundingCurrent: 0,
    fundingGoal: 40000,
    backerCount: 0,
    waitlistCount: 45,
    gradient: 'from-blue-500 to-cyan-400',
    features: [
      'Joins Zoom, Meet, and Teams calls automatically',
      '5-bullet summary, not a transcript wall',
      'Creates tasks in Linear, Jira, or Notion automatically',
      'Searches meeting history by topic, not keyword',
      'Drafts follow-up emails with assigned action items',
    ],
    milestones: [
      { id: 'm1', title: 'Validation open — testing demand signal', completed: true, dueDate: '2026-04-01' },
      { id: 'm2', title: 'Funding phase opens on strong signal', completed: false, dueDate: '2026-07-01' },
    ],
    comments: [
      { id: 'c1', author: 'PM Life', initials: 'PL', avatarColor: '#67E8F9', content: 'Otter gives me a transcript. That\'s not the same as notes. The real problem is turning conversation into action — this gets it.', createdAt: '2026-05-15', likes: 44 },
    ],
    tags: ['meetings', 'ai', 'productivity', 'automation'],
    createdAt: '2026-03-22',
  },
  {
    id: '10',
    title: 'PitchDeck.ai',
    slug: 'pitchdeck-ai',
    tagline: 'Describe your startup. Get an investor-ready deck in minutes.',
    description: '1,102 upvotes from founders who\'ve spent 40+ hours on pitch decks proved the pain is real. PitchDeck.ai converts a plain-English description of your startup into a professional deck with real market data, competitor analysis, and financial templates — without hiring a designer or consultant.',
    category: 'AI',
    status: 'IN_DEV',
    upvotes: 1102,
    downvotes: 45,
    fundingCurrent: 45000,
    fundingGoal: 45000,
    backerCount: 623,
    gradient: 'from-violet-600 to-purple-800',
    features: [
      'AI slide generation from text description',
      'Live market size data from Crunchbase and PitchBook',
      'Competitor landscape analysis',
      'Financial projection templates',
      'One-click export to PowerPoint or PDF',
    ],
    milestones: [
      { id: 'm1', title: 'Validation — 1,102 upvotes, 623 waitlist', completed: true, dueDate: '2026-02-15' },
      { id: 'm2', title: 'Slide generation engine + market data', completed: true, dueDate: '2026-04-01' },
      { id: 'm3', title: 'Template library + export', completed: false, dueDate: '2026-06-01' },
    ],
    developer: mockDevelopers[1],
    comments: [
      { id: 'c1', author: 'First-time Founder', initials: 'FF', avatarColor: '#A78BFA', content: 'I spent 40 hours on my last deck. If this actually works with real market data it\'s worth 10x whatever it costs.', createdAt: '2026-04-05', likes: 78 },
    ],
    tags: ['ai', 'startups', 'fundraising', 'presentations'],
    createdAt: '2025-12-20',
  },
  {
    id: '11',
    title: 'BeatDrop',
    slug: 'beatdrop',
    tagline: 'Make beats with friends in your browser — no DAW, no install',
    description: '723 upvotes from music producers confirmed the frustration: collaborative music production requires everyone to own the same expensive software. BeatDrop is a browser-based DAW with real-time collaboration for up to 8 people — professional results without a subscription that costs more than a month of groceries.',
    category: 'SOCIAL',
    status: 'FUNDING',
    upvotes: 723,
    downvotes: 34,
    fundingCurrent: 15000,
    fundingGoal: 40000,
    backerCount: 298,
    gradient: 'from-fuchsia-600 to-pink-500',
    features: [
      'Real-time collaborative sessions, up to 8 people',
      'Browser-based — no install, no subscription gatekeeping',
      '1,000+ professional samples included',
      'Export stems and master track',
      'Beat marketplace for sharing and monetising',
    ],
    milestones: [
      { id: 'm1', title: 'Validation — 723 upvotes confirmed the gap', completed: true, dueDate: '2026-03-01' },
      { id: 'm2', title: 'Core audio engine', completed: true, dueDate: '2026-04-15' },
      { id: 'm3', title: 'Real-time collaboration engine', completed: false, dueDate: '2026-06-15' },
      { id: 'm4', title: 'Sample library + marketplace', completed: false, dueDate: '2026-08-01' },
    ],
    comments: [
      { id: 'c1', author: 'Beat Maker', initials: 'BM', avatarColor: '#F9A8D4', content: 'SoundTrap but actually good. The collab angle is the entire point — I produce remotely with 3 other people and we\'re all using different setups.', createdAt: '2026-05-02', likes: 62 },
    ],
    tags: ['music', 'collab', 'audio', 'creator'],
    createdAt: '2026-02-28',
  },
  {
    id: '12',
    title: 'LegalEasy',
    slug: 'legaleasy',
    tagline: 'Upload any contract. Know what you\'re signing in 30 seconds.',
    description: 'Signed a freelance contract last month with a clause I didn\'t understand. A lawyer would\'ve cost $500 for a $3K project — that math doesn\'t work. Testing whether freelancers, renters, and small business owners want an AI tool that analyzes any contract and tells you: what does this mean, what\'s risky, what should you push back on.',
    category: 'FINTECH',
    status: 'VOTING',
    upvotes: 94,
    downvotes: 5,
    fundingCurrent: 0,
    fundingGoal: 35000,
    backerCount: 0,
    waitlistCount: 8,
    gradient: 'from-teal-500 to-green-600',
    features: [
      'Plain-English summary of any contract in 30 seconds',
      'Risk flags for clauses that are unusual or unfavorable',
      'Comparison against standard contract templates',
      'Suggested negotiation points',
      'Supports NDAs, freelance agreements, leases, employment contracts',
    ],
    milestones: [
      { id: 'm1', title: 'Validation phase — testing demand', completed: true, dueDate: '2026-04-01' },
      { id: 'm2', title: 'Legal compliance review', completed: false, dueDate: '2026-07-01' },
    ],
    comments: [
      { id: 'c1', author: 'Freelancer', initials: 'FL', avatarColor: '#6EE7B7', content: 'I\'ve signed things I didn\'t fully understand because lawyers cost too much for small contracts. This is needed by millions of people.', createdAt: '2026-05-20', likes: 91 },
    ],
    tags: ['legal', 'contracts', 'ai', 'freelance'],
    createdAt: '2026-04-01',
  },
  {
    id: '13',
    title: 'GamePulse',
    slug: 'gamepulse',
    tagline: 'Live esports analytics — every game, one dashboard',
    description: 'Validated by 1,876 upvotes asking "why is there no Bloomberg Terminal for esports?" GamePulse aggregates live match data, player performance, team analytics, and historical stats across 15 major esports titles. Now live with a developer API in beta used by betting platforms and content creators.',
    category: 'GAMING',
    status: 'LIVE',
    upvotes: 1876,
    downvotes: 71,
    fundingCurrent: 55000,
    fundingGoal: 55000,
    backerCount: 1102,
    gradient: 'from-red-600 to-orange-500',
    features: [
      'Live match data across 15+ esports titles',
      'Player and team performance analytics',
      '5-year historical data archive',
      'Developer API with Discord bot integration',
      'Custom alert rules for match events',
    ],
    milestones: [
      { id: 'm1', title: 'Validation — 1,876 upvotes confirmed market', completed: true, dueDate: '2025-10-01' },
      { id: 'm2', title: 'Data pipeline + dashboard v1', completed: true, dueDate: '2025-12-01' },
      { id: 'm3', title: 'API beta program', completed: true, dueDate: '2026-03-01' },
      { id: 'm4', title: '50K active users milestone', completed: false, dueDate: '2026-08-01' },
    ],
    developer: mockDevelopers[0],
    comments: [
      { id: 'c1', author: 'EsportsAnalyst', initials: 'EA', avatarColor: '#FED7AA', content: 'This replaced 3 other tools I was using. The LoL and Dota 2 coverage is genuinely better than anything else out there.', createdAt: '2026-04-28', likes: 178 },
    ],
    tags: ['gaming', 'esports', 'analytics', 'data'],
    createdAt: '2025-09-15',
  },
  {
    id: '14',
    title: 'DevPulse',
    slug: 'devpulse',
    tagline: 'One dashboard for your GitHub, Linear, and Jira activity',
    description: 'End-of-quarter review and I spent 3 hours manually compiling what I shipped across 6 tools to write a 10-bullet impact summary. Testing whether developers want a unified activity dashboard that automatically tells the story of what you built — for perf reviews, for your own clarity, or just to know where the week went.',
    category: 'DEVELOPER_TOOLS',
    status: 'VOTING',
    upvotes: 42,
    downvotes: 4,
    fundingCurrent: 0,
    fundingGoal: 20000,
    backerCount: 0,
    waitlistCount: 3,
    gradient: 'from-sky-500 to-blue-700',
    features: [
      'Pull activity from GitHub, GitLab, Linear, Jira automatically',
      'Daily/weekly/monthly summaries in plain English',
      'Auto-generate standup updates',
      'Context-switch cost analysis (where the day actually went)',
      'One-pager export for perf reviews',
    ],
    milestones: [
      { id: 'm1', title: 'Validation open — early signal stage', completed: true, dueDate: '2026-05-01' },
      { id: 'm2', title: 'Funding phase on confirmed signal', completed: false, dueDate: '2026-08-01' },
    ],
    comments: [
      { id: 'c1', author: 'IC Engineer', initials: 'IE', avatarColor: '#67E8F9', content: 'Perfect for impact documentation during perf cycles. I currently manually track everything in a Notion doc I never remember to update.', createdAt: '2026-05-22', likes: 38 },
    ],
    tags: ['developer-tools', 'analytics', 'github', 'productivity'],
    createdAt: '2026-04-28',
  },
  {
    id: '15',
    title: 'HealthLedger',
    slug: 'healthledger',
    tagline: 'Your health records, actually portable',
    description: 'Moved cities last year and had to recreate my entire medical history from scratch — my old GP\'s system doesn\'t export. Every specialist starts from zero. Testing demand for a personal health record wallet: you aggregate everything (labs, prescriptions, imaging, wearables), you own it, you share specific pieces with each new doctor.',
    category: 'HEALTH',
    status: 'VOTING',
    upvotes: 18,
    downvotes: 2,
    fundingCurrent: 0,
    fundingGoal: 50000,
    backerCount: 0,
    waitlistCount: 1,
    gradient: 'from-rose-500 to-pink-600',
    features: [
      'FHIR-compliant import from major hospital systems',
      'Connect Apple Health, Fitbit, Garmin wearables',
      'Granular sharing — give each doctor only what they need',
      'Timeline view of your full health history',
      'Emergency access for nominated family members',
    ],
    milestones: [
      { id: 'm1', title: 'Validation open — early signal stage', completed: true, dueDate: '2026-04-15' },
      { id: 'm2', title: 'Privacy architecture + HIPAA compliance review', completed: false, dueDate: '2026-07-15' },
      { id: 'm3', title: 'Funding phase open', completed: false, dueDate: '2026-09-01' },
    ],
    comments: [
      { id: 'c1', author: 'Privacy Advocate', initials: 'PA', avatarColor: '#F9A8D4', content: 'This is critical infrastructure. Every time I see a new specialist I start from zero. The problem is real.', createdAt: '2026-05-25', likes: 52 },
    ],
    tags: ['health', 'privacy', 'records', 'wearables'],
    createdAt: '2026-04-10',
  },
]

export const mockUser: UserProfile = {
  id: 'user-1',
  name: 'Jordan Blake',
  username: 'jordanblake',
  initials: 'JB',
  avatarColor: '#7C3AED',
  joinedAt: '2025-09-01',
  stats: {
    totalVotes: 247,
    totalBacked: 8,
    totalSubmitted: 3,
    reputation: 1840,
    totalFunded: 3200,
  },
  badges: [
    {
      id: 'b1',
      name: 'Signal Caller',
      description: 'Upvoted 5+ ideas that went on to reach PROVEN DEMAND',
      emoji: '📡',
      color: 'orange',
      earned: true,
    },
    {
      id: 'b2',
      name: 'Super Backer',
      description: 'Backed 5+ projects that shipped successfully',
      emoji: '💎',
      color: 'cyan',
      earned: true,
    },
    {
      id: 'b3',
      name: 'Early Adopter',
      description: 'Joined AppDrop in the first 90 days',
      emoji: '⚡',
      color: 'purple',
      earned: true,
    },
    {
      id: 'b4',
      name: 'Idea Validator',
      description: 'Submitted 3+ ideas that passed BUILDING tier',
      emoji: '🧪',
      color: 'pink',
      earned: true,
    },
    {
      id: 'b5',
      name: 'First Shipper',
      description: 'Claim a validated project and ship it to LIVE',
      emoji: '🚀',
      color: 'orange',
      earned: false,
    },
    {
      id: 'b6',
      name: 'Community Voice',
      description: 'Leave 100+ comments that get upvoted as helpful signal',
      emoji: '📣',
      color: 'cyan',
      earned: false,
    },
  ],
}
